services:
  backend:
    build:
      context: ../pucrio-arq-backend
      dockerfile: Dockerfile
    container_name: tech4bike-backend
    ports:
      - "8000:8000"
    environment:
      - DB_PATH=/app/data/tech4bike.db
    volumes:
      - backend_data:/app/data
    restart: always

  frontend:
    build: .
    container_name: tech4bike-frontend
    ports:
      - "3000:3000"
    environment:
      - API_URL=http://tech4bike-backend:8000/api/v1
      - NEXT_PUBLIC_API_URL=http://localhost:8000/api/v1
    depends_on:
      - backend
    restart: always

volumes:
  backend_data: